import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar"
import Filter from "../components/Filter"
import Tools from "../components/Tools"
import Footer from "../components/Footer"

export default function Home() {
	return ( 
		<div className="">
			<Head>
				<title>HeadlessCommerce</title>
				<meta name="description" content="Generated by create next app" />
        		<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="lg:px-60">
				<Navbar />
			</div>
			<div className="bg-[#f9fafb] ">
				<Filter />
				
				<div className="pb-10 lg:px-60">
					<Tools />
				</div>
			</div>
			<Footer />
		</div>
	 );
}
 
