import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar"
import Filter from "../components/Filter"
import Tools from "../components/Tools"
import Footer from "../components/Footer"

export default function Home() {
	return ( 
		<div>
			<Head>
				<title>HeadlessCommerce</title>
				<meta name="description" content="Generated by create next app" />
        		<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar />
			<div className="bg-[#f9fafb]">
				<Filter />
				<div className="px-5">
					<Tools />
				</div>
			</div>
			<Footer />
		</div>
	 );
}
 
